version: "3.8"
networks:
  oran-sc-ric_ric_network:
    external: true
    name: oran-sc-ric_ric_network

services:  
  du:
    image: guilhermemaciel75/ud:v0.0.11-metrics
    ports:
      - target: 36421
        published: 36421
        protocol: tcp
        mode: host
      - target: 2000
        published: 2000
        protocol: tcp
        mode: host

    networks:
      ran:
        aliases:
          - du_ran
      f1:
        aliases:
          - du_f1
      #oran-sc-ric_ric_network:
      #  aliases:
      #    - ric_network

    environment:
      E2_BIND_ADDR: "0.0.0.0" 
      F1AP_BIND_ADDR: "0.0.0.0"
      RU_SDR_TX_PORT: "10.45.0.1"
      RU_SDR_RX_PORT: "10.45.0.1"
      F1AP_CU_CP_ADDR: "oran_cu_cu"
      GNB_ID : "1"
         

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  ran:
    external: true
    name: "docker_ran"

  f1:
    external: true
    name: "docker_f1"

  #oran-sc-ric_ric_network:
  #  external: true
  #  name: "oran-sc-ric_ric_network"

